/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Reports service status and database connectivity (runs SELECT 1).
         */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/surahs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all surahs
         * @description Returns all 114 surahs, ordered by number.
         */
        get: operations["SurahsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/surahs/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a surah by number or UCI */
        get: operations["SurahsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/surahs/{identifier}/ayahs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the ayahs of a surah
         * @description Ayahs of the surah in order, each with text in the requested editions.
         */
        get: operations["SurahsController_findAyahs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ayahs/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an ayah
         * @description Fetch a single ayah with text in the requested editions.
         */
        get: operations["AyahsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List editions
         * @description All editions, optionally filtered by language and/or type.
         */
        get: operations["EditionsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/editions/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an edition by slug, number, or UCI */
        get: operations["EditionsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/juzs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all juzs */
        get: operations["DivisionsController_listJuzs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/juzs/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a juz by number or UCI */
        get: operations["DivisionsController_getJuz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/juzs/{identifier}/ayahs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the ayahs of a juz */
        get: operations["DivisionsController_juzAyahs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hizbs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all hizbs */
        get: operations["DivisionsController_listHizbs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hizbs/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a hizb by number or UCI */
        get: operations["DivisionsController_getHizb"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hizbs/{identifier}/ayahs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the ayahs of a hizb */
        get: operations["DivisionsController_hizbAyahs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all rubs */
        get: operations["DivisionsController_listRubs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubs/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a rub by number or UCI */
        get: operations["DivisionsController_getRub"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubs/{identifier}/ayahs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the ayahs of a rub */
        get: operations["DivisionsController_rubAyahs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rukus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all rukus */
        get: operations["DivisionsController_listRukus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rukus/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a ruku by number or UCI */
        get: operations["DivisionsController_getRuku"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rukus/{identifier}/ayahs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the ayahs of a ruku */
        get: operations["DivisionsController_rukuAyahs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manzils": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all manzils */
        get: operations["DivisionsController_listManzils"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manzils/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a manzil by number or UCI */
        get: operations["DivisionsController_getManzil"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manzils/{identifier}/ayahs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the ayahs of a manzil */
        get: operations["DivisionsController_manzilAyahs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthDto: {
            /**
             * @description Overall service status
             * @enum {string}
             */
            status: "ok" | "error";
            /**
             * @description Database connectivity
             * @enum {string}
             */
            db: "up" | "down";
        };
        SurahDto: {
            /** @description Unique Content Identifier, 'QS' + number (e.g. QS2) */
            uci: string;
            /** @description Surah number, 1–114 */
            number: number;
            /** @description Arabic name (e.g. البقرة) */
            nameArabic: string;
            /** @description English name (e.g. Al-Baqara) */
            nameEnglish: string;
            /**
             * @description Where the surah was revealed
             * @enum {string}
             */
            revelationPlace: "meccan" | "medinan";
            /** @description Chronological order of revelation */
            revelationOrder: number;
            /** @description Number of ayahs in the surah */
            ayahCount: number;
            /** @description Number of rukus in the surah */
            rukuCount: number;
            /** @description True when a bismillah header precedes the surah */
            bismillahPrefix: boolean;
        };
        AyahWithTextDto: {
            /** @description Unique Content Identifier, 'QA' + number (e.g. QA262) */
            uci: string;
            /** @description Global ayah number, 1–6236 */
            number: number;
            /** @description UCI of the surah this ayah belongs to */
            surahUci: string;
            /** @description Position within the surah */
            numberInSurah: number;
            /**
             * @description Type of prostration, null if none
             * @enum {string|null}
             */
            sajda: "recommended" | "obligatory" | null;
            /** @description UCI of the containing juz */
            juzUci: string;
            /** @description UCI of the containing hizb */
            hizbUci: string;
            /** @description UCI of the containing rub */
            rubUci: string;
            /** @description UCI of the containing ruku */
            rukuUci: string;
            /** @description UCI of the containing manzil */
            manzilUci: string;
            /** @description Renderings in the requested editions, in requested order */
            texts: {
                /** @description Edition slug (e.g. quran-simple) */
                edition: string;
                /** @description Edition display name */
                name: string;
                /** @description Edition language code */
                language: string;
                /**
                 * @description Kind of text rendering
                 * @enum {string}
                 */
                type: "original" | "translation" | "transliteration";
                /** @description The ayah text in this edition */
                text: string;
                /** @description Bismillah header, only on the first ayah of qualifying surahs */
                bismillah: string | null;
            }[];
        };
        EditionDto: {
            /** @description Unique Content Identifier, 'QE' + number (e.g. QE1) */
            uci: string;
            /** @description Edition number */
            number: number;
            /** @description Stable handle for lookups (e.g. quran-simple) */
            slug: string;
            /** @description Edition display name */
            name: string;
            /** @description Edition language code */
            language: string;
            /**
             * @description Kind of text rendering
             * @enum {string}
             */
            type: "original" | "translation" | "transliteration";
        };
        JuzDto: {
            /** @description UCI, 'QJ' + number (e.g. QJ1) */
            uci: string;
            /** @description Juz number, 1–30 */
            number: number;
            /** @description First global ayah number */
            startAyahNumber: number;
            /** @description Last global ayah number */
            endAyahNumber: number;
        };
        HizbDto: {
            /** @description UCI, 'QH' + number (e.g. QH1) */
            uci: string;
            /** @description Hizb number, 1–60 */
            number: number;
            /** @description UCI of the containing juz */
            juzUci: string;
            /** @description Position within the juz */
            numberInJuz: number;
        };
        RubDto: {
            /** @description UCI, 'QR' + number (e.g. QR1) */
            uci: string;
            /** @description Rub number, 1–240 */
            number: number;
            /** @description UCI of the containing hizb */
            hizbUci: string;
            /** @description Position within the hizb */
            numberInHizb: number;
            /** @description Position within the juz */
            numberInJuz: number;
            /** @description First global ayah number */
            startAyahNumber: number;
            /** @description Last global ayah number */
            endAyahNumber: number;
        };
        RukuDto: {
            /** @description UCI, 'QK' + number (e.g. QK1) */
            uci: string;
            /** @description Ruku number, 1–556 */
            number: number;
            /** @description UCI of the containing surah */
            surahUci: string;
            /** @description Position within the surah */
            numberInSurah: number;
            /** @description UCI of the containing juz */
            juzUci: string;
            /** @description Position within the juz */
            numberInJuz: number;
            /** @description First global ayah number */
            startAyahNumber: number;
            /** @description Last global ayah number */
            endAyahNumber: number;
            /** @description Number of ayahs in the ruku */
            ayahCount: number;
        };
        ManzilDto: {
            /** @description UCI, 'QM' + number (e.g. QM1) */
            uci: string;
            /** @description Manzil number, 1–7 */
            number: number;
            /** @description UCI of the first surah */
            startSurahUci: string;
            /** @description UCI of the last surah */
            endSurahUci: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    SurahsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurahDto"][];
                };
            };
        };
    };
    SurahsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Surah number (e.g. 2) or UCI (e.g. QS2) */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurahDto"];
                };
            };
            /** @description No surah matches the identifier */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SurahsController_findAyahs: {
        parameters: {
            query?: {
                /** @description Comma-separated edition slugs, numbers, or UCIs (default: quran-simple) */
                edition?: string;
            };
            header?: never;
            path: {
                /** @description Surah number (e.g. 2) or UCI (e.g. QS2) */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AyahWithTextDto"][];
                };
            };
            /** @description No surah matches the identifier, or an edition is unknown */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AyahsController_findOne: {
        parameters: {
            query?: {
                /** @description Comma-separated edition slugs, numbers, or UCIs (default: quran-simple) */
                edition?: string;
            };
            header?: never;
            path: {
                /** @description Global ayah number (e.g. 262), UCI (e.g. QA262), or 'surah:ayah' (e.g. 2:255) */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AyahWithTextDto"];
                };
            };
            /** @description No ayah matches the identifier, or an edition is unknown */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EditionsController_findAll: {
        parameters: {
            query?: {
                /** @description Filter by language code (e.g. en, ur) */
                language?: string;
                /** @description Filter by edition type */
                type?: "original" | "translation" | "transliteration";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditionDto"][];
                };
            };
        };
    };
    EditionsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Edition slug (e.g. quran-simple), number (e.g. 1), or UCI (e.g. QE1) */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditionDto"];
                };
            };
            /** @description No edition matches the identifier */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_listJuzs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JuzDto"][];
                };
            };
        };
    };
    DivisionsController_getJuz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Juz number (e.g. 1) or UCI */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JuzDto"];
                };
            };
            /** @description No juz matches the identifier */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_juzAyahs: {
        parameters: {
            query?: {
                /** @description Comma-separated edition slugs, numbers, or UCIs (default: quran-simple) */
                edition?: string;
            };
            header?: never;
            path: {
                /** @description Juz number (e.g. 1) or UCI */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AyahWithTextDto"][];
                };
            };
            /** @description No juz matches the identifier, or an edition is unknown */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_listHizbs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HizbDto"][];
                };
            };
        };
    };
    DivisionsController_getHizb: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Hizb number (e.g. 1) or UCI */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HizbDto"];
                };
            };
            /** @description No hizb matches the identifier */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_hizbAyahs: {
        parameters: {
            query?: {
                /** @description Comma-separated edition slugs, numbers, or UCIs (default: quran-simple) */
                edition?: string;
            };
            header?: never;
            path: {
                /** @description Hizb number (e.g. 1) or UCI */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AyahWithTextDto"][];
                };
            };
            /** @description No hizb matches the identifier, or an edition is unknown */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_listRubs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubDto"][];
                };
            };
        };
    };
    DivisionsController_getRub: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rub number (e.g. 1) or UCI */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubDto"];
                };
            };
            /** @description No rub matches the identifier */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_rubAyahs: {
        parameters: {
            query?: {
                /** @description Comma-separated edition slugs, numbers, or UCIs (default: quran-simple) */
                edition?: string;
            };
            header?: never;
            path: {
                /** @description Rub number (e.g. 1) or UCI */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AyahWithTextDto"][];
                };
            };
            /** @description No rub matches the identifier, or an edition is unknown */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_listRukus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RukuDto"][];
                };
            };
        };
    };
    DivisionsController_getRuku: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ruku number (e.g. 1) or UCI */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RukuDto"];
                };
            };
            /** @description No ruku matches the identifier */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_rukuAyahs: {
        parameters: {
            query?: {
                /** @description Comma-separated edition slugs, numbers, or UCIs (default: quran-simple) */
                edition?: string;
            };
            header?: never;
            path: {
                /** @description Ruku number (e.g. 1) or UCI */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AyahWithTextDto"][];
                };
            };
            /** @description No ruku matches the identifier, or an edition is unknown */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_listManzils: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManzilDto"][];
                };
            };
        };
    };
    DivisionsController_getManzil: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Manzil number (e.g. 1) or UCI */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManzilDto"];
                };
            };
            /** @description No manzil matches the identifier */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DivisionsController_manzilAyahs: {
        parameters: {
            query?: {
                /** @description Comma-separated edition slugs, numbers, or UCIs (default: quran-simple) */
                edition?: string;
            };
            header?: never;
            path: {
                /** @description Manzil number (e.g. 1) or UCI */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AyahWithTextDto"][];
                };
            };
            /** @description No manzil matches the identifier, or an edition is unknown */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
